/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tadeapps.View;

/**
 *
 * @author ranaufal
 */
public class VMenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public VMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtUsernamePegawai = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jBtnMaster = new javax.swing.JButton();
        jBtnPengeluaran = new javax.swing.JButton();
        jBtnPayroll = new javax.swing.JButton();
        jBtnTransaksi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(246, 222, 136));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 140));

        jLabel1.setBackground(new java.awt.Color(246, 222, 136));
        jLabel1.setFont(new java.awt.Font("Kannada MN", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(8, 43, 89));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1144, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(246, 222, 136));

        txtUsernamePegawai.setFont(new java.awt.Font("Kannada MN", 0, 18)); // NOI18N
        txtUsernamePegawai.setForeground(new java.awt.Color(204, 0, 51));
        txtUsernamePegawai.setText("usernamepegawai");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtUsernamePegawai)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(txtUsernamePegawai)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(246, 222, 136));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(246, 222, 136));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(246, 222, 136));
        jPanel6.setLayout(null);

        jBtnMaster.setFont(new java.awt.Font("Kannada MN", 0, 24)); // NOI18N
        jBtnMaster.setForeground(new java.awt.Color(8, 43, 89));
        jBtnMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/master-icon.png"))); // NOI18N
        jBtnMaster.setText("Master Data");
        jBtnMaster.setPreferredSize(new java.awt.Dimension(129, 60));
        jBtnMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMasterActionPerformed(evt);
            }
        });
        jPanel6.add(jBtnMaster);
        jBtnMaster.setBounds(170, 70, 270, 130);

        jBtnPengeluaran.setFont(new java.awt.Font("Kannada MN", 0, 24)); // NOI18N
        jBtnPengeluaran.setForeground(new java.awt.Color(8, 43, 89));
        jBtnPengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/master-icon.png"))); // NOI18N
        jBtnPengeluaran.setText("Pengeluaran");
        jBtnPengeluaran.setPreferredSize(new java.awt.Dimension(129, 60));
        jBtnPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPengeluaranActionPerformed(evt);
            }
        });
        jPanel6.add(jBtnPengeluaran);
        jBtnPengeluaran.setBounds(180, 290, 270, 130);

        jBtnPayroll.setFont(new java.awt.Font("Kannada MN", 0, 24)); // NOI18N
        jBtnPayroll.setForeground(new java.awt.Color(8, 43, 89));
        jBtnPayroll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/master-icon.png"))); // NOI18N
        jBtnPayroll.setText("Payroll");
        jBtnPayroll.setPreferredSize(new java.awt.Dimension(129, 60));
        jBtnPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPayrollActionPerformed(evt);
            }
        });
        jPanel6.add(jBtnPayroll);
        jBtnPayroll.setBounds(510, 290, 270, 130);

        jBtnTransaksi.setFont(new java.awt.Font("Kannada MN", 0, 24)); // NOI18N
        jBtnTransaksi.setForeground(new java.awt.Color(8, 43, 89));
        jBtnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/master-icon.png"))); // NOI18N
        jBtnTransaksi.setText("Transaksi");
        jBtnTransaksi.setPreferredSize(new java.awt.Dimension(129, 60));
        jBtnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTransaksiActionPerformed(evt);
            }
        });
        jPanel6.add(jBtnTransaksi);
        jBtnTransaksi.setBounds(510, 70, 270, 130);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPayrollActionPerformed
        // TODO add your handling code here:
        dispose();
        new VDataGajiSaatIni().setVisible(true);
    }//GEN-LAST:event_jBtnPayrollActionPerformed

    private void jBtnMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMasterActionPerformed
        // TODO add your handling code here:
        dispose();
        new VMasterMenu().setVisible(true);
    }//GEN-LAST:event_jBtnMasterActionPerformed

    private void jBtnPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPengeluaranActionPerformed
        // TODO add your handling code here:
        dispose();
        new VMenuPengeluaran().setVisible(true);
    }//GEN-LAST:event_jBtnPengeluaranActionPerformed

    private void jBtnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTransaksiActionPerformed
        // TODO add your handling code here:
        dispose();
        new VTransaksi().setVisible(true);
    }//GEN-LAST:event_jBtnTransaksiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new VLogin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnMaster;
    private javax.swing.JButton jBtnPayroll;
    private javax.swing.JButton jBtnPengeluaran;
    private javax.swing.JButton jBtnTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel txtUsernamePegawai;
    // End of variables declaration//GEN-END:variables
}
